# Generated by Django 4.2.3 on 2023-07-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=225)),
                ('alamat', models.CharField(max_length=225)),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=225)),
                ('golongan', models.CharField(choices=[('pembina - I/A', 'pembina - I/A'), ('pembina - II/A', 'pembina - II/A'), ('pembina - III/A', 'pembina - III/A'), ('pembina - II/B', 'pembina - II/B'), ('penata - I/A', 'penata - I/A'), ('penata - II/A', 'penata - II/A'), ('penata - III/A', 'penata - III/A')], max_length=225)),
            ],
        ),
    ]
