# Generated by Django 4.2.3 on 2023-07-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=225)),
                ('alamat', models.CharField(max_length=225)),
                ('umur', models.IntegerField(max_length=2)),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='Pegawai',
        ),
    ]
